# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'shoppingGuideApp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

	pod 'AlibcTradeSDK'

  # Pods for react_native_calendar

end

